import React from "react";
import { Activity, Code2, Crosshair, Layers, Radio } from "lucide-react";
import { profile } from "../../lib/profile";
import OperatorAvatar from "./OperatorAvatar";
import DeveloperTelemetry from "./DeveloperTelemetry";
const statusRows = [
  { label: "MODE", value: "Frontend Developer // Systems UI", icon: Code2, tone: "text-neon-blue" },
  { label: "BUILD", value: "Byteprowler v2", icon: Activity, tone: "text-neon-lime" },
  { label: "FOCUS", value: "React, Next.js, Tailwind, TypeScript", icon: Layers, tone: "text-neon-purple" },
  { label: "NEXT", value: "Fullstack systems, APIs, testing", icon: Crosshair, tone: "text-neon-green" },
];

export default function OperatorStatusPanel() {
  return (
    <aside className="flex w-full flex-col gap-4 rounded-sm border border-neon-lime/15 bg-black/70 p-4 font-mono shadow-inner neon-border-lime">
      <div className="flex items-center justify-between gap-3 border-b border-neon-lime/15 pb-3 text-[11px] uppercase tracking-widest text-gray-300">
        <span className="font-black text-neon-lime">[ CURRENT_ARC_STATUS ]</span>
        <span className="text-neon-green">READY</span>
      </div>

      <div className="flex flex-col gap-4 sm:flex-row md:flex-col">
        {/* Replace or update this file with the generated Byteprowler operator avatar: public/avatar/operator-avatar-placeholder.png */}
        <OperatorAvatar
          imageSrc="/avatar/operator-avatar-placeholder.png"
          label="OPERATOR_AVATAR"
          status="ARC_ACTIVE"
          className="w-full sm:max-w-[15rem] md:max-w-none md:items-stretch"
        />

        <div className="grid min-w-0 flex-1 grid-cols-1 gap-2.5">
          {statusRows.map((row) => {
            const Icon = row.icon;
            return (
              <div key={row.label} className="rounded-sm border border-white/5 bg-[#08090d]/75 px-3 py-2.5">
                <div className="mb-1 flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-gray-300">
                  <Icon className={`h-3.5 w-3.5 ${row.tone}`} aria-hidden="true" />
                  <span>{row.label}</span>
                </div>
                <p className="break-words text-xs font-bold uppercase leading-relaxed text-white">
                  {row.value}
                </p>
              </div>
            );
          })}
        </div>
      </div>
      <DeveloperTelemetry />
      <div className="rounded-sm border border-neon-lime/15 bg-neon-lime/5 px-3 py-2.5 text-[11px] leading-relaxed text-gray-200">
        <div className="mb-1 flex items-center gap-2 font-black uppercase tracking-widest text-neon-lime">
          <Radio className="h-3.5 w-3.5" aria-hidden="true" />
          <span>STATUS</span>
        </div>
        <p>
          {`${profile.availabilityStatus.split("_").join(" ")} // Build production-ready web interfaces for work, collaboration, and growth opportunities.`}
        </p>
      </div>
    </aside>
  );
}

